package com.mrjaffesclass.apcs.mvc.template;
import com.mrjaffesclass.apcs.messenger.*;
import java.util.Hashtable;
import javax.swing.JFrame;
import javax.swing.JSlider;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import javax.swing.JLabel;
import javax.swing.*;

/**
 * MVC Template
 * This is a template of an MVC framework used by APCS for the 
 * LandMine project (and others)
 * @author Roger Jaffe
 * @version 1.0
 * 
 */
public class View extends javax.swing.JFrame implements MessageHandler {

  private final Messenger mvcMessaging;
  private String displayAnswer;
  
  /**
   * Creates a new view
   * @param messages mvcMessaging object
   */
  public View(Messenger messages) {
    mvcMessaging = messages;   // Save the calling controller instance
    initComponents();           // Create and init the GUI components
  }
  
  /**
   * Initialize the model here and subscribe
   * to any required messages
   */
  public void init() {
    // Subscribe to messages here
    mvcMessaging.subscribe("model:answerChanged", this);
    mvcMessaging.subscribe("model:hairColor2Changed", this);
    
     
    buttonGroupGender.add(jRadioMale);
    buttonGroupGender.add(jRadioFemale);
    
    buttonGroupHairColor.add(jRadioButtonHairBrown);
    buttonGroupHairColor.add(jRadioButtonHairBlack);
    buttonGroupHairColor.add(jRadioButtonHairRed);
    buttonGroupHairColor.add(jRadioButtonHairBlonde);
    buttonGroupHairColor.add(jRadioButtonHairGrey);
    
    buttonGroupEyeColor.add(jRadioButtonEyeBlue);
    buttonGroupEyeColor.add(jRadioButtonEyeBrown);
    buttonGroupEyeColor.add(jRadioButtonEyeGreen);
    buttonGroupEyeColor.add(jRadioButtonEyeHazel);
    buttonGroupEyeColor.add(jRadioButtonEyeBlack);

    jSliderAge.getModel().setMinimum(15);
    jSliderAge.getModel().setMaximum(80);
    jSliderAge.setPaintTicks(true);
    jSliderAge.setMajorTickSpacing(80);
    jSliderAge.setMinorTickSpacing(1);
    jSliderAge.setPaintLabels(true);
    Hashtable ht = jSliderAge.createStandardLabels(5);
    jSliderAge.setLabelTable(ht);

    jSliderAge.addChangeListener(new ChangeListener() {
      public void stateChanged(ChangeEvent e) {
        //System.out.println("jSliderAge: " + jSliderAge.getValue());
        mvcMessaging.notify("view:AgeChanged", jSliderAge.getValue(), true);
      }
    });
        
        
    jSliderHeight.getModel().setMinimum(48);
    jSliderHeight.getModel().setMaximum(84);
    jSliderHeight.setPaintTicks(true);
    jSliderHeight.setMajorTickSpacing(12);
    jSliderHeight.setMinorTickSpacing(1);
    
    Hashtable labelTable = new Hashtable();
    labelTable.put( new Integer( 48 ), new JLabel("4'0") );
    labelTable.put( new Integer( 54 ), new JLabel("4'6") );
    labelTable.put( new Integer( 60 ), new JLabel("5'0") );
    labelTable.put( new Integer( 66 ), new JLabel("5'6") );
    labelTable.put( new Integer( 72 ), new JLabel("6'0") );
    labelTable.put( new Integer( 78 ), new JLabel("6'6") );
    labelTable.put( new Integer( 84 ), new JLabel("7'0") );
    jSliderHeight.setLabelTable( labelTable );

    jSliderHeight.setPaintLabels(true);


    jSliderHeight.addChangeListener(new ChangeListener() {
      public void stateChanged(ChangeEvent e) {
        //System.out.println("jSliderHeight: " + jSliderHeight.getValue());
        mvcMessaging.notify("view:HeightChanged", jSliderHeight.getValue(), true);
      }
    });
    
 
  }
  
  @Override
  public void messageHandler(String messageName, Object messagePayload) {
    if (messagePayload != null) {
      System.out.println("MSG: received by view: "+messageName+" | "+messagePayload.toString());
    } else {
      System.out.println("MSG: received by view: "+messageName+" | No data sent");
    }
    if (messageName.equals("model:answerChanged")) {
      displayAnswer = (messagePayload.toString());
    } 
  }

  /**
   * Instantiate an object with the field number that was clicked (1 or 2) and
   * the direction that the number should go (up or down)
   * @param fieldNumber 1 or 2 for the field being modified
   * @param direction this.UP (1) or this.DOWN (-1), constants defined above
   * @return the HashMap payload to be sent with the message
   */
  private MessagePayload createPayload(int fieldNumber, int direction) {
    MessagePayload payload = new MessagePayload(fieldNumber, direction);
    return payload;
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupGender = new javax.swing.ButtonGroup();
        buttonGroupHairColor = new javax.swing.ButtonGroup();
        buttonGroupEyeColor = new javax.swing.ButtonGroup();
        jPopupAnswer = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jRadioMale = new javax.swing.JRadioButton();
        jRadioFemale = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        jRadioButtonHairBrown = new javax.swing.JRadioButton();
        jRadioButtonEyeGreen = new javax.swing.JRadioButton();
        jRadioButtonHairBlonde = new javax.swing.JRadioButton();
        jRadioButtonHairRed = new javax.swing.JRadioButton();
        jRadioButtonEyeBlue = new javax.swing.JRadioButton();
        jRadioButtonEyeBrown = new javax.swing.JRadioButton();
        jSliderAge = new javax.swing.JSlider();
        jRadioButtonEyeHazel = new javax.swing.JRadioButton();
        jRadioButtonHairBlack = new javax.swing.JRadioButton();
        jRadioButtonHairGrey = new javax.swing.JRadioButton();
        jRadioButtonEyeBlack = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        jSliderHeight = new javax.swing.JSlider();
        jButtonSubmit = new javax.swing.JButton();

        javax.swing.GroupLayout jPopupAnswerLayout = new javax.swing.GroupLayout(jPopupAnswer.getContentPane());
        jPopupAnswer.getContentPane().setLayout(jPopupAnswerLayout);
        jPopupAnswerLayout.setHorizontalGroup(
            jPopupAnswerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPopupAnswerLayout.setVerticalGroup(
            jPopupAnswerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Simplified Arabic", 1, 18)); // NOI18N
        jLabel1.setText("What's your gender?");

        jLabel5.setFont(new java.awt.Font("Simplified Arabic", 1, 18)); // NOI18N
        jLabel5.setText("What is your age?");
        jLabel5.setMaximumSize(new java.awt.Dimension(45, 60));

        jLabel6.setFont(new java.awt.Font("Simplified Arabic", 1, 18)); // NOI18N
        jLabel6.setText("What hair color do you prefer on a partner?");

        jRadioMale.setFont(new java.awt.Font("Simplified Arabic", 0, 18)); // NOI18N
        jRadioMale.setText("Male");
        jRadioMale.setToolTipText("");
        jRadioMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioMaleActionPerformed(evt);
            }
        });

        jRadioFemale.setFont(new java.awt.Font("Simplified Arabic", 0, 18)); // NOI18N
        jRadioFemale.setText("Female");
        jRadioFemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioFemaleActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Simplified Arabic", 1, 18)); // NOI18N
        jLabel12.setText("What eye color do you prefer in a partner?");

        jRadioButtonHairBrown.setFont(new java.awt.Font("Simplified Arabic", 0, 18)); // NOI18N
        jRadioButtonHairBrown.setText("Brown");
        jRadioButtonHairBrown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonHairBrownActionPerformed(evt);
            }
        });
        jRadioButtonHairBrown.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jRadioButtonHairBrownKeyPressed(evt);
            }
        });

        jRadioButtonEyeGreen.setFont(new java.awt.Font("Simplified Arabic", 0, 18)); // NOI18N
        jRadioButtonEyeGreen.setText("Green");
        jRadioButtonEyeGreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonEyeGreenActionPerformed(evt);
            }
        });

        jRadioButtonHairBlonde.setFont(new java.awt.Font("Simplified Arabic", 0, 18)); // NOI18N
        jRadioButtonHairBlonde.setText("Blonde");
        jRadioButtonHairBlonde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonHairBlondeActionPerformed(evt);
            }
        });

        jRadioButtonHairRed.setFont(new java.awt.Font("Simplified Arabic", 0, 18)); // NOI18N
        jRadioButtonHairRed.setText("Red");
        jRadioButtonHairRed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonHairRedActionPerformed(evt);
            }
        });

        jRadioButtonEyeBlue.setFont(new java.awt.Font("Simplified Arabic", 0, 18)); // NOI18N
        jRadioButtonEyeBlue.setText("Blue");
        jRadioButtonEyeBlue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonEyeBlueActionPerformed(evt);
            }
        });

        jRadioButtonEyeBrown.setFont(new java.awt.Font("Simplified Arabic", 0, 18)); // NOI18N
        jRadioButtonEyeBrown.setText("Brown");
        jRadioButtonEyeBrown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonEyeBrownActionPerformed(evt);
            }
        });

        jRadioButtonEyeHazel.setFont(new java.awt.Font("Simplified Arabic", 0, 18)); // NOI18N
        jRadioButtonEyeHazel.setText("Hazel");
        jRadioButtonEyeHazel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonEyeHazelActionPerformed(evt);
            }
        });

        jRadioButtonHairBlack.setFont(new java.awt.Font("Simplified Arabic", 0, 18)); // NOI18N
        jRadioButtonHairBlack.setText("Black");
        jRadioButtonHairBlack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonHairBlackActionPerformed(evt);
            }
        });

        jRadioButtonHairGrey.setFont(new java.awt.Font("Simplified Arabic", 0, 18)); // NOI18N
        jRadioButtonHairGrey.setText("Grey");
        jRadioButtonHairGrey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonHairGreyActionPerformed(evt);
            }
        });

        jRadioButtonEyeBlack.setFont(new java.awt.Font("Simplified Arabic", 0, 18)); // NOI18N
        jRadioButtonEyeBlack.setText("Black");
        jRadioButtonEyeBlack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonEyeBlackActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Simplified Arabic", 1, 18)); // NOI18N
        jLabel13.setText("How tall would you want your partner to be?");

        jButtonSubmit.setBackground(new java.awt.Color(120, 240, 0));
        jButtonSubmit.setFont(new java.awt.Font("Kabel", 0, 24)); // NOI18N
        jButtonSubmit.setForeground(new java.awt.Color(0, 20, 240));
        jButtonSubmit.setText("Submit");
        jButtonSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jButtonSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(34, 34, 34)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jRadioButtonHairBrown)
                                                    .addComponent(jRadioButtonEyeBrown))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jRadioButtonEyeBlack)
                                                    .addComponent(jRadioButtonHairBlack)))))
                                    .addComponent(jLabel12))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jRadioButtonEyeBlue)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                                        .addComponent(jRadioButtonHairBlonde)
                                        .addGap(8, 8, 8)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButtonHairRed)
                                    .addComponent(jRadioButtonEyeHazel))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButtonEyeGreen)
                                    .addComponent(jRadioButtonHairGrey)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(30, 30, 30)
                                        .addComponent(jRadioMale)
                                        .addGap(27, 27, 27)
                                        .addComponent(jRadioFemale)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(23, 23, 23))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jSliderHeight, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jSliderAge, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(44, 44, 44))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jRadioMale)
                    .addComponent(jRadioFemale))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSliderAge, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSliderHeight, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButtonEyeBlue)
                    .addComponent(jRadioButtonEyeBrown)
                    .addComponent(jRadioButtonEyeBlack)
                    .addComponent(jRadioButtonEyeHazel)
                    .addComponent(jRadioButtonEyeGreen))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonHairBrown)
                    .addComponent(jRadioButtonHairBlonde)
                    .addComponent(jRadioButtonHairRed)
                    .addComponent(jRadioButtonHairBlack)
                    .addComponent(jRadioButtonHairGrey)
                    .addComponent(jLabel6))
                .addGap(39, 39, 39)
                .addComponent(jButtonSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonHairBrownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonHairBrownActionPerformed
        // TODO add your handling code here:
        mvcMessaging.notify("view:hairColorChanged", "Brown", true);
    }//GEN-LAST:event_jRadioButtonHairBrownActionPerformed

    private void jRadioButtonHairBrownKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jRadioButtonHairBrownKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jRadioButtonHairBrownKeyPressed

    private void jRadioButtonEyeGreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonEyeGreenActionPerformed
        // TODO add your handling code here:
      mvcMessaging.notify("view:eyeColorChanged", "Green", true);
    }//GEN-LAST:event_jRadioButtonEyeGreenActionPerformed

    private void jRadioButtonHairBlackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonHairBlackActionPerformed
        // TODO add your handling code here:
       mvcMessaging.notify("view:hairColorChanged", "Black", true);

    }//GEN-LAST:event_jRadioButtonHairBlackActionPerformed

    private void jRadioButtonHairGreyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonHairGreyActionPerformed
        // TODO add your handling code here:
      mvcMessaging.notify("view:hairColorChanged", "Grey", true);
    }//GEN-LAST:event_jRadioButtonHairGreyActionPerformed

    private void jRadioMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioMaleActionPerformed
        // TODO add your handling code here:
      mvcMessaging.notify("view:GenderChanged", "Male", true);
        
    }//GEN-LAST:event_jRadioMaleActionPerformed

    private void jRadioFemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioFemaleActionPerformed
        // TODO add your handling code here:
      mvcMessaging.notify("view:GenderChanged", "Female", true);
    }//GEN-LAST:event_jRadioFemaleActionPerformed

    private void jRadioButtonHairRedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonHairRedActionPerformed
        // TODO add your handling code here:
      mvcMessaging.notify("view:hairColorChanged", "Red", true);
    }//GEN-LAST:event_jRadioButtonHairRedActionPerformed

    private void jRadioButtonEyeBlueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonEyeBlueActionPerformed
      mvcMessaging.notify("view:eyeColorChanged", "Blue", true);
    }//GEN-LAST:event_jRadioButtonEyeBlueActionPerformed

    private void jRadioButtonEyeBrownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonEyeBrownActionPerformed
      mvcMessaging.notify("view:eyeColorChanged", "Brown", true);
    }//GEN-LAST:event_jRadioButtonEyeBrownActionPerformed

    private void jRadioButtonEyeHazelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonEyeHazelActionPerformed
      mvcMessaging.notify("view:eyeColorChanged", "Hazel", true);
    }//GEN-LAST:event_jRadioButtonEyeHazelActionPerformed

    private void jRadioButtonEyeBlackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonEyeBlackActionPerformed
      mvcMessaging.notify("view:eyeColorChanged", "Black", true);
    }//GEN-LAST:event_jRadioButtonEyeBlackActionPerformed

    private void jButtonSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubmitActionPerformed
        JOptionPane.showMessageDialog(null, displayAnswer);
    }//GEN-LAST:event_jButtonSubmitActionPerformed

    private void jRadioButtonHairBlondeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonHairBlondeActionPerformed
      mvcMessaging.notify("view:hairColorChanged", "Blonde", true);
    }//GEN-LAST:event_jRadioButtonHairBlondeActionPerformed

  /**
   * @param args the command line arguments
   */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupEyeColor;
    private javax.swing.ButtonGroup buttonGroupGender;
    private javax.swing.ButtonGroup buttonGroupHairColor;
    private javax.swing.JButton jButtonSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JDialog jPopupAnswer;
    private javax.swing.JRadioButton jRadioButtonEyeBlack;
    private javax.swing.JRadioButton jRadioButtonEyeBlue;
    private javax.swing.JRadioButton jRadioButtonEyeBrown;
    private javax.swing.JRadioButton jRadioButtonEyeGreen;
    private javax.swing.JRadioButton jRadioButtonEyeHazel;
    private javax.swing.JRadioButton jRadioButtonHairBlack;
    private javax.swing.JRadioButton jRadioButtonHairBlonde;
    private javax.swing.JRadioButton jRadioButtonHairBrown;
    private javax.swing.JRadioButton jRadioButtonHairGrey;
    private javax.swing.JRadioButton jRadioButtonHairRed;
    private javax.swing.JRadioButton jRadioFemale;
    private javax.swing.JRadioButton jRadioMale;
    private javax.swing.JSlider jSliderAge;
    private javax.swing.JSlider jSliderHeight;
    // End of variables declaration//GEN-END:variables

  

}
